[package]
name = "riker"
version = "0.1.2"
authors = ["Lee Smith <leenozara@gmail.com>"]
description = "Easily build fast, highly concurrent and resilient applications. An Actor Framework for Rust."
homepage = "https://riker.rs"
repository = "https://github.com/riker-rs/riker"
license = "MIT"
readme = "README.md"
keywords = ["actors", "async"]

[badges]
travis-ci = { repository = "riker-rs/riker" }

[dependencies]
bytes = "0.4"
chrono = "0.4"
config = "0.8"
futures-preview = "0.2.2"
log = { version = "0.4", features = ["std"] }
rand = "0.4"
regex = "0.2"
uuid = { version = "0.6", features = ["v4"] }

[dev-dependencies]
riker-default = { path = "riker-default", version = "0.1.2" }
riker-testkit = "0.1.0"
