[package]
name = "riker-macros"
version = "0.1.0"
authors = ["Lee Smith <lee@riker.rs>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version ="0.15", features = ['full'] }
quote = "0.6.3"
proc-macro2 = "*"
